### ISSUE TITLE
Update action to remove deprecation warnings

### ISSUE THREAD

**Issue by facutuesca** [dblock/create-a-github-issue#10]
Currently, running this action generates the following warnings:

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: dblock/create-a-github-issue
```
and
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

There's a recently merged PR on the upstream repo (https://github.com/JasonEtco/create-an-issue/pull/137) that I believe fixes them. Would it be possible to include those commits in this fork?

**Comment by dblock** [comment]
@facutuesca Yes, care to contribute? Thanks.

**Comment by dblock** [comment]
I setup renovate, check HEAD, lmk what else is needed and I'll cut a release.

**Comment by facutuesca** [comment]
@dblock It works perfectly, thanks!
