### ISSUE TITLE
Upgrade action to node 20

### ISSUE THREAD

**Issue by pkwarren** [dblock/create-a-github-issue#121]
We're seeing a warning in our builds with this action:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: dblock/create-a-github-issue@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Is it possible to upgrade this action to target Node 20?

**Comment by dblock** [comment]
Probably. Please PR!
