### ISSUE TITLE
Support cross repo issue create

### ISSUE THREAD

**Issue by prudhvigodithi** [dblock/create-a-github-issue#71]
Coming from https://github.com/opensearch-project/opensearch-build/pull/3708 the existing `dblock/create-a-github-issue@v3.0.0` does not support creating issues for cross repo. I'm trying to create multiple issues from a workflow which uses `dblock/create-a-github-issue@v3.0.0`  running in a standalone repo, even though the github_token used from an app that has access across multiple repos, the action `dblock/create-a-github-issue@v3.0.0` does not support creating issues in different repo.

The code that has `tools.context.repo` should be replaced with choice injected by env.
@dblock

**Comment by dblock** [comment]
Dup of https://github.com/dblock/create-a-github-issue/issues/8. will close. Want to try to contribute?
